import {mkdir,writeFile,cp,rm} from 'node:fs/promises';
import {profile,projects} from './content.mjs';
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
await rm('dist',{recursive:true,force:true}); await mkdir('dist',{recursive:true}); await cp('public','dist',{recursive:true});
const nav=(active='')=>`<header><a class="brand" href="/">${esc(profile.name)}<span> / PORTFOLIO</span></a><nav aria-label="Main navigation"><a ${active==='work'?'aria-current="page"':''} href="/work/">Work <small>05</small></a><a ${active==='about'?'aria-current="page"':''} href="/about/">About</a><a href="/contact/">Contact</a></nav><span class="header-meta">${esc(profile.location)} / SELECTED WORK</span></header>`;
const footer=()=>`<footer><a href="/">${esc(profile.name)} / Architecture & interactive design</a><a href="/contact/">Let’s connect</a><span>© ${new Date().getFullYear()} ${esc(profile.name)}</span></footer>`;
const shell=(title,body,active='')=>`<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="description" content="${esc(profile.name)} — architecture student working across architecture, product design, UX/UI and 3D interactive experiences."><meta name="theme-color" content="#f7f7f2"><title>${esc(title)} — ${esc(profile.name)}</title><link rel="icon" href="/favicon.svg"><link rel="stylesheet" href="/style.css"><script type="module" src="/app.js"></script></head><body><a class="skip" href="#main">Skip to content</a>${nav(active)}<main id="main">${body}</main>${footer()}</body></html>`;
const visual=(p,large=false)=>`<div class="visual ${p.accent} ${large?'large':''}">${p.image?`<img src="${esc(p.image)}" alt="${esc(p.title)} project visual" loading="lazy">`:`<canvas data-drawing="${p.category}" aria-hidden="true"></canvas><span class="visual-label">FIG. ${p.number} / ${esc(p.note)}</span><span class="placeholder">${p.category==='Architecture'?'DRAWING':'IMAGE'} PLACEHOLDER</span><span class="crosshair">+</span>`}</div>`;
const card=p=>`<article class="project" data-category="${p.category}"><a href="/work/${p.slug}/" aria-label="View ${esc(p.title)}">${visual(p)}<div class="card-info"><span class="index">${p.number}</span><div><h3>${esc(p.title)}</h3><p>${esc(p.disciplines)}</p></div><span class="project-type">${p.category}</span></div></a></article>`;
const grid=()=>`<div class="project-grid">${projects.map(card).join('')}</div>`;
const contact=()=>profile.email?`<a class="text-link" href="mailto:${esc(profile.email)}">${esc(profile.email)}</a>`:`<p class="pending">Contact details will be added soon.</p>`;
const resume=()=>profile.resume?`<a class="text-link" href="${esc(profile.resume)}" download>Download résumé</a>`:`<span class="pending">Résumé coming soon</span>`;
await writeFile('dist/index.html',shell('Architecture & interactive design',`<section class="hero"><div class="hero-top"><span class="eyebrow">AN EVOLVING PRACTICE / 01—05</span><span class="eyebrow">SPACE · PEOPLE · INTERACTION</span></div><h1>Thinking in spaces.<br>Designing <em>connections.</em></h1><div class="hero-board"><div class="hero-note note-a"><span class="eyebrow">01 / PHYSICAL</span><p>Architecture<br>& spatial systems</p></div><canvas id="hero-drawing" aria-label="Abstract computational spatial diagram, a placeholder for an architectural model" role="img"></canvas><div class="hero-note note-b"><span class="eyebrow">02 / DIGITAL</span><p>Products, worlds<br>& experiences</p></div><span class="hero-coordinate">STUDY 001 / CONCEPTUAL GEOMETRY</span><span class="hero-caption">[ MODEL PLACEHOLDER ]</span></div><div class="hero-bottom"><p>I'm ${esc(profile.name)}. An architecture student exploring the space between built environments and digital experiences.</p><a class="pill" href="#selected">Explore selected work <span>05</span></a></div></section><section id="selected" class="work-section"><div class="section-heading"><span class="eyebrow">INDEX / SELECTED WORK</span><h2>Across disciplines.<br><em>One curious practice.</em></h2><p>Architecture, products and virtual worlds — brought together by an interest in people and the spaces they inhabit.</p></div>${grid()}<a class="text-link" href="/work/">Explore the full index</a></section><section class="about-strip"><span class="eyebrow">A NOTE ABOUT ME</span><h2>Between the drawing board<br>and the <em>digital world.</em></h2><p>${esc(profile.intro)}</p><a class="text-link" href="/about/">More about my practice</a></section>`));
await mkdir('dist/work',{recursive:true});await writeFile('dist/work/index.html',shell('Work',`<section class="page-intro"><span class="eyebrow">PROJECT INDEX / 01—05</span><h1>Selected <em>work.</em></h1><p>A practice moving between architecture, products and interactive worlds.</p></section><section class="work-section"><div class="filters" aria-label="Filter projects">${['All','Architecture','Product','Interactive','Personal'].map((c,i)=>`<button type="button" data-filter="${c}" aria-pressed="${i===0}">${c}</button>`).join('')}</div><p id="filter-status" class="sr-only" aria-live="polite"></p>${grid()}</section>`,'work'));
for(const p of projects){await mkdir(`dist/work/${p.slug}`,{recursive:true});await writeFile(`dist/work/${p.slug}/index.html`,shell(p.title,`<section class="case-intro"><a class="back-link" href="/work/">Back to work index</a><div class="case-title"><span class="eyebrow">PROJECT ${p.number} / ${p.category}</span><h1>${esc(p.title)}</h1><p>${esc(p.summary)}</p></div><div class="case-meta"><div><span class="eyebrow">MY ROLE</span><p>${esc(p.role)}</p></div><div><span class="eyebrow">DISCIPLINES</span><p>${esc(p.disciplines)}</p></div><div><span class="eyebrow">PROJECT RECORD</span><p>Draft / images to follow</p></div></div>${visual(p,true)}</section><section class="case-body">${p.sections.map(([title,body],i)=>`<article><span class="eyebrow">0${i+1}</span><div><h2>${esc(title)}</h2><p>${esc(body)}</p>${i===1?`<div class="process-slots"><div><span>01 / PROCESS</span><p>Image placeholder</p></div><div><span>02 / DEVELOPMENT</span><p>Image placeholder</p></div></div>`:''}</div></article>`).join('')}</section><section class="next-project"><span class="eyebrow">NEXT IN THE INDEX</span><a href="/work/${projects[(projects.indexOf(p)+1)%projects.length].slug}/">${esc(projects[(projects.indexOf(p)+1)%projects.length].title)}</a></section>`,'work'));}
await mkdir('dist/about',{recursive:true});await writeFile('dist/about/index.html',shell('About',`<section class="page-intro"><span class="eyebrow">ABOUT / ${esc(profile.name)}</span><h1>Space to think.<br><em>Room to explore.</em></h1></section><section class="about-layout"><div class="portrait-placeholder"><span class="eyebrow">PORTRAIT / PLACEHOLDER</span><span class="portrait-letter">${esc(profile.name.charAt(0))}.</span></div><div class="about-copy"><h2>Architecture is<br>my starting point.</h2><p>${esc(profile.intro)}</p><p>My work spans architectural and computational studies, the UX and 3D world of a gamified social app, and a phonics product-design project. Each asks a different version of the same question: how can design shape an experience?</p><div class="practice-list"><span>01 / Architecture & computational design</span><span>02 / Product design & UX/UI</span><span>03 / 3D environments & characters</span><span>04 / Interactive experiences</span></div><div class="about-links">${resume()}<a class="text-link" href="/contact/">Get in touch</a></div></div></section>`,'about'));
await mkdir('dist/contact',{recursive:true});await writeFile('dist/contact/index.html',shell('Contact',`<section class="contact-page"><span class="eyebrow">CONTACT / START A CONVERSATION</span><h1>Good things begin<br>with a <em>conversation.</em></h1><p>For collaborations, opportunities or a conversation about design.</p>${contact()}<div class="contact-bottom"><div><span class="eyebrow">BASED IN</span><p>${esc(profile.location)}</p></div><div><span class="eyebrow">RÉSUMÉ</span><p>${resume()}</p></div></div></section>`));
await writeFile('dist/404.html',shell('Page not found',`<section class="page-intro"><span class="eyebrow">404 / OUTSIDE THE DRAWING</span><h1>Let’s find<br>our <em>way back.</em></h1><a class="text-link" href="/work/">Explore selected work</a></section>`));
console.log('Built 10 pages in dist.');
